creation_timestamp: 1767053710933
current_stage: None
deployment_job_state: null
description: 'YOLO11n课堂行为检测模型 - mAP50: 0.4536'
last_updated_timestamp: 1767053710933
model_id: null
name: classroom_behavior_yolo11n
run_id: 38196c379fab40c8a8b8cd9598e9cfb7
run_link: null
source: file:///D:/archive/runs/mlflow/743216558863757798/38196c379fab40c8a8b8cd9598e9cfb7/artifacts/model/best.pt
status: READY
status_message: null
storage_location: file:///D:/archive/runs/mlflow/743216558863757798/38196c379fab40c8a8b8cd9598e9cfb7/artifacts/model/best.pt
user_id: null
version: 1
